### ISSUE TITLE
WASM: fix sending i8/u8/i16/u16

### ISSUE THREAD

**Issue by wngr** [cloudpeers/ffi-gen#34]
https://github.com/cloudpeers/ffi-gen/pull/33#discussion_r762188059

**Comment by wngr** [comment]
I guess this doesn't matter much, as the wasm stack machine does not support u8 num types. For dart we still use u8.

**Comment by dvc94ch** [comment]
Well in the unlikely case someone really wants to return a u8 there's nothing stopping them, and they'll run into trouble. Maybe we can lower u8 and u16 as i32 on wasm?
