### ISSUE TITLE
Call flutter callback from rust side

### ISSUE THREAD

**Issue by bitfriend** [cloudpeers/ffi-gen#71]
I am working on `flutter-rust-bridget` based project.
I am going to call flutter callback from rust side, but I have no idea about how to define this callback in `api.rsh`.
I hope your great help.

**Comment by dvc94ch** [comment]
callbacks are tricky with dart. the problem being that the callback address is only valid if the "right" isolate is running. they have ports you can use to send a notification to switch to the isolate. from there you can call a regular ffi method to get the result. as you can probably already guess, this matches the rust Future/Stream perfectly. We register a custom waker that uses the port and have the poll method return the result. So if you have a FnOnce callback it would be a Future and a FnMut callback would be a Stream. Let me know if you have any trouble with futures or streams.

**Comment by bitfriend** [comment]
Thank you for your explanation.
I am on stream-based solution.

**Comment by bitfriend** [comment]
Can you please write the simple code here?
`rust`, `api.rsh`, `dart`
I have no idea about what code should be written for `stream` in `api.rsh`.
How the `stream` type is dealt in `api.rsh`?

**Comment by dvc94ch** [comment]
Ah there's a bug with Stream<()>. You can try Stream<u32> and then take it from there. Ffi-gen is still experimental
